NK  Hú ş Nş HKş Nú  BÜÜÛÛÛÛÛÛÜÜW  HKÚNÄHÄÄNÄHKÄÙ  NÚHKÄ¿N  HKÚÄN¿  HKÀÄNÄHÄÄNÄHK¿N‚BÜÜH4ÜÜ ÜÜÜNBÜÜWƒú HKş Nş HKş ú
ú ş Nş ş HúN‚BÛ4ÛÛÛHWNOAAN4BÛÛÛWÜH0K  ÚÄNÄHÄÄNÄHKÄÄÙ úN  HKú ÀÄÄNÄHÄÄNÄHKÄ¿  NBÜH4WßÛÜBßßİÛÛßßÜÜNBÜWƒHú ş Nş HKş ú
Nú HKş Nş Hş Nú  H7B N4ÛÜÜ0BÛÛÛÛÛÛ4WÜÛÛH7BÜN‚HB*N RNATIONALW RWEATHERW HB*N‚BŞH4ßÛÜWßÛÜ  NBÛH4ßßÛßÜNBİW‚ú Hş Nş HKş Nú
Hú Kş Nş Hş Kú BŞ7ÛÜN4ÛÛÛÜÜ0BÛÛ4WÛH7BÜÜ0ÛÛİN‡RSERVICEW‰BÛH4ßNBÛH4W ÜÜÛß N4    HBßNBÛÛW‚HKú Wş Nş HKş Wú
Nú HKş Nş Hş Nú  HBÛÛÛÛ7ßß N4ÛH7BÜÜÜ0ÛÛÛN™BßH4W ÜÜ ÜßÛÜ   ÜÛßNBßW‚ú Hş Nş HKş Nú
HKú ş Nş ş HúN‚HBÛÛÛÛÛÛÛÛÛÛÛÛN‚Ú HKlogos drawn poorlyN ¿‚BßÛH4WßÛÛÛÜßÜßÛÛNBÛßWƒHú Nş ş HKş ú
W  Kú ş Nş HKş Nú  HBßßÛÛÛÛÛÛßßNƒHKÀN HKwithout permissionN HKÙN„BßßH4ßßßß WßÜNBßWƒú HKş Nş HKş ú
NÃÄHKÄNÄHKÄÄÄNÄHKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄNÄHKÄÄÄNÄHKÄNÄ´
HK³N‚This is a simple weather forecast reader for Synchronet BBS written†HK³
Nú‚in JavascriptHK.N It makes use of several online APIs to gather and‰ú
HKúN‚display weather forecast data given a specified locationHK.NHKú
NúÌú
HKúN‚The National Weather Service HK(WweatherN.HgovK)N is its primary source of†HKú
úN‚forecast data for US citiesHK.N If an international city is specifiedHK,N†HKú
úN‚or if weatherHK.Ngov is unavailableHK,N then data from Open WeatherHK'Ns One†HKú
úN‚Call API HK(WopenweathermapN.HorgK)N is used insteadHK.N›HKú
úNÌHKú
úN‚If there is an RaHctivNReH NRaHlerNRtW in the forecast areaHK,N a brief description„HKú
úN‚is displayed with the option to view the detailsHK.N˜HKú
úNÌHKú
úN‚These services require a locationHK'Ns latitude and longitude to query†HKú
úN‚forecast dataHK.N HoweverHK,N since the average person likely does not know„HKú
úN‚the latitude and longitude for most world citiesHK,N options are available‚HKú
úN‚to help determine them by using a cityHK'Ns name or an IP address insteadHK.N‚HKú
úN‚These geocoding services are provided by HgeocodeN.HmapsN.Hco NandHKú
úN‚HfreeipapiN.HcomN respectivelyHK.N®HKú
úNÌHKú
úN‚As yet another fun bonusHK,N if youHK'Nre using HSyncTERMK,N you can view‰HKú
úN‚current weather maps and satellite images in glorious HKSNIHXNEHKLN!HKú
úN‚Images are sourced from HNOAAN.HGOVN, HWeatherN.HgovN, and HwwwN.HssecN.HwiscN.HeduK.N„HKú
úNÌHKú
úN‚Of course itHK'Ns worth mentioning that if any or all of these APIs go†HKú
úN‚offline or are changed significantlyHK, Nthen this reader could cease to„HKú
úN‚function properlyHK. NSo thereHK'Ns thatHK.N¦HKú
NúÌú
HK³N‚Enjoy!ÃHK³
NÃÄHKÄNÄHKÄÄÄNÄHKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄNÄHKÄÄÄNÄHKÄNÄ´
Z